In [2]:
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/AI/TS_Eamcet/output.csv')

In [4]:
df

,Inst_\rcode,Institution Name,Branch\rCode,Roll_No,Rank,Candidate Name,Gend\rer,Regio\rn,Caste\rCode,Seat_\rCategory
0,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2124D03737,144,KOTA VIGNAN,M,OU,BC_B,OC_GEN_UR
1,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2126D02627,233,SONABOYINA NIKHIL TEJA,M,OU,BC_D,OC_GEN_UR
2,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2123I03036,243,RACHAKONDA ESHWAR,M,OU,BC_B,BC_B_GEN_UR
3,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2125D03084,286,CHALLA RUPAK VARDHAN,M,OU,OC,EWS_GEN_UR
4,JNTH,"JNTU COLLEGE OF ENGG HYDERABAD, HYDERABAD",CSE,2124E09174,318,SHRIYANS MEDIPELLY,M,OU,BC_D,BC_D_GEN_OU
...,...,...,...,...,...,...,...,...,...,...
58729,SWET,"SHADHAN WOMENS COLL OF ENGG AND TECHNOLOGY, KH...",INF,900002980,300294,SANIA IRFAN,F,OU,BC_E,MUS_GIRLS_OU
58730,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900003312,300295,MOHAMMED MUSTAFA,M,OU,BC_E,MUS_GEN_OU
58731,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900002905,300307,HANZALAH SYED ASIF,M,OU,OC,MUS_GEN_OU
58732,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900003073,300312,MOHD KHAJA ZUHAIRUDDIN,M,OU,BC_E,MUS_GEN_UR
58733,DCET,"DECCAN COLLEGE OF ENGINEERING AND TECHNOLOGY, ...",CIV,900002990,300315,AMENA HIBA,F,OU,BC_E,MUS_GEN_OU

In [5]:
df.columns

Index(['Inst_\rcode', 'Institution Name', 'Branch\rCode', 'Roll_No', 'Rank',
       'Candidate Name', 'Gend\rer', 'Regio\rn', 'Caste\rCode',
       'Seat_\rCategory'],
      dtype='object')

In [6]:
df = df.rename(columns = {'Inst_\rcode':'Institute_Code','Branch\rCode':'Branch_Code','Gend\rer':'Gender','Regio\rn':'Region','Caste\rCode':'Caste_Code','Seat_\rCategory':'Seat_Category'})

In [7]:
df

,Institute_Code,Institution Name,Branch_Code,Roll_No,Rank,Candidate Name,Gender,Region,Caste_Code,Seat_Category
0,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2124D03737,144,KOTA VIGNAN,M,OU,BC_B,OC_GEN_UR
1,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2126D02627,233,SONABOYINA NIKHIL TEJA,M,OU,BC_D,OC_GEN_UR
2,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2123I03036,243,RACHAKONDA ESHWAR,M,OU,BC_B,BC_B_GEN_UR
3,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2125D03084,286,CHALLA RUPAK VARDHAN,M,OU,OC,EWS_GEN_UR
4,JNTH,"JNTU COLLEGE OF ENGG HYDERABAD, HYDERABAD",CSE,2124E09174,318,SHRIYANS MEDIPELLY,M,OU,BC_D,BC_D_GEN_OU
...,...,...,...,...,...,...,...,...,...,...
58729,SWET,"SHADHAN WOMENS COLL OF ENGG AND TECHNOLOGY, KH...",INF,900002980,300294,SANIA IRFAN,F,OU,BC_E,MUS_GIRLS_OU
58730,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900003312,300295,MOHAMMED MUSTAFA,M,OU,BC_E,MUS_GEN_OU
58731,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900002905,300307,HANZALAH SYED ASIF,M,OU,OC,MUS_GEN_OU
58732,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900003073,300312,MOHD KHAJA ZUHAIRUDDIN,M,OU,BC_E,MUS_GEN_UR
58733,DCET,"DECCAN COLLEGE OF ENGINEERING AND TECHNOLOGY, ...",CIV,900002990,300315,AMENA HIBA,F,OU,BC_E,MUS_GEN_OU

In [8]:
df = df[df["Rank"].str.contains("Rank") == False]

In [9]:
df['Rank'] = df['Rank'].astype(str).astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
df.query("Branch_Code in ( 'AID','CSM','AIM','CSD','CSE','CSI','CSM','CME','CSN','CST','INF','ITE') and Caste_Code == 'BC_D' and Gender =='F' and Region == 'OU' and Institute_Code in ('MRCE', 'CBIT') and Seat_Category in ('BC_D_GIRLS_OU','BC_D_GEN_OU') and Rank >= 1000 and Rank <= 50000 ")

,Institute_Code,Institution Name,Branch_Code,Roll_No,Rank,Candidate Name,Gender,Region,Caste_Code,Seat_Category
309,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",CSE,2121I06033,1771,VAJJE DEEPANVITHA,F,OU,BC_D,BC_D_GIRLS_OU
491,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",CSE,2122A01380,2292,PILLA TRIVENI,F,OU,BC_D,BC_D_GIRLS_OU
539,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",CSE,2123Q03004,2413,THOTA NIKHITHA,F,OU,BC_D,BC_D_GIRLS_OU
599,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",CSE,2124B07050,2578,TEJOMAI GOURU,F,OU,BC_D,BC_D_GIRLS_OU
679,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",CSE,2124A03987,2768,VASAM PRIYANKA,F,OU,BC_D,BC_D_GIRLS_OU
688,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",CSM,2125E12003,2798,K S SATHWIKHA,F,OU,BC_D,BC_D_GIRLS_OU
711,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",CSM,2121J01069,2848,MAREPALLI NAVYA SREE,F,OU,BC_D,BC_D_GIRLS_OU
836,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",INF,2123H01068,3137,POLEBOINA DIVYA,F,OU,BC_D,BC_D_GEN_OU
894,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AIM,2121A02173,3268,DODLA ANUSHKA,F,OU,BC_D,BC_D_GIRLS_OU
917,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AIM,2123E02124,3306,BHAGYA SREE,F,OU,BC_D,BC_D_GEN_OU
1243,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AID,2125I03160,3970,UMMIDI MOHANA SREE,F,OU,BC_D,BC_D_GIRLS_OU
1622,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AIM,2122L01021,4756,MARGAM HARINI,F,OU,BC_D,BC_D_GIRLS_OU
1638,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",INF,2125E12059,4783,THOTA DIVYA SREE,F,OU,BC_D,BC_D_GIRLS_OU
1907,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",INF,2122Q03116,5280,VENUKANTI MAMATHA,F,OU,BC_D,BC_D_GIRLS_OU
2182,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AID,2124E11034,5787,ARYA MAHATHI,F,OU,BC_D,BC_D_GIRLS_OU
2436,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AID,2126A02654,6287,GANDHAM SAI AKSHITHA,F,OU,BC_D,BC_D_GIRLS_OU
2863,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AID,2121E09021,7032,BUGGALA JAHNAVI,F,OU,BC_D,BC_D_GIRLS_OU
2890,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",AID,2125D09044,7091,JAMALPUR NAVYA SREE,F,OU,BC_D,BC_D_GEN_OU
3568,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",INF,2121A03976,8309,THAVIDISETTI A J SRI SARAYU,F,OU,BC_D,BC_D_GIRLS_OU
3834,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",INF,2126L05088,8789,LANDERI SHIVANI,F,OU,BC_D,BC_D_GIRLS_OU
4571,CBIT,"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY, GA...",INF,2124D02471,10103,RANGA RISHITHA,F,OU,BC_D,BC_D_GIRLS_OU
21244,MRCE,"MALLA REDDY COLLEGE OF ENGINEERING, MYSAMMAGUDA",CSE,2123E02163,39211,GHANORE AARTHI,F,OU,BC_D,BC_D_GIRLS_OU
21340,MRCE,"MALLA REDDY COLLEGE OF ENGINEERING, MYSAMMAGUDA",CSE,2123E04163,39392,TADI PETTI PAVANI,F,OU,BC_D,BC_D_GIRLS_OU
24173,MRCE,"MALLA REDDY COLLEGE OF ENGINEERING, MYSAMMAGUDA",CSE,2125I05137,44597,RASALA BHUMIKA,F,OU,BC_D,BC_D_GIRLS_OU

In [11]:
df

,Institute_Code,Institution Name,Branch_Code,Roll_No,Rank,Candidate Name,Gender,Region,Caste_Code,Seat_Category
0,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2124D03737,144,KOTA VIGNAN,M,OU,BC_B,OC_GEN_UR
1,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2126D02627,233,SONABOYINA NIKHIL TEJA,M,OU,BC_D,OC_GEN_UR
2,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2123I03036,243,RACHAKONDA ESHWAR,M,OU,BC_B,BC_B_GEN_UR
3,MVSR,"M V S R ENGINEERING COLLEGE (AUTONOMOUS), NADE...",CSE,2125D03084,286,CHALLA RUPAK VARDHAN,M,OU,OC,EWS_GEN_UR
4,JNTH,"JNTU COLLEGE OF ENGG HYDERABAD, HYDERABAD",CSE,2124E09174,318,SHRIYANS MEDIPELLY,M,OU,BC_D,BC_D_GEN_OU
...,...,...,...,...,...,...,...,...,...,...
58729,SWET,"SHADHAN WOMENS COLL OF ENGG AND TECHNOLOGY, KH...",INF,900002980,300294,SANIA IRFAN,F,OU,BC_E,MUS_GIRLS_OU
58730,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900003312,300295,MOHAMMED MUSTAFA,M,OU,BC_E,MUS_GEN_OU
58731,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900002905,300307,HANZALAH SYED ASIF,M,OU,OC,MUS_GEN_OU
58732,SCET,"SHADHAN COLL OF ENGINEERING AND TECHNOLOGY, PE...",AID,900003073,300312,MOHD KHAJA ZUHAIRUDDIN,M,OU,BC_E,MUS_GEN_UR
58733,DCET,"DECCAN COLLEGE OF ENGINEERING AND TECHNOLOGY, ...",CIV,900002990,300315,AMENA HIBA,F,OU,BC_E,MUS_GEN_OU

In [12]:
#Institute_Code in ('') 
#df.query("Branch_Code in ( 'AID','CSM','AIM','CSD','CSE','CSI','CSM','CME','CSN','CST','INF','ITE') and Caste_Code == 'BC_D' and Gender =='M' and Institute_Code in ('OUCE','JNTH','CBIT','VASV','VJEC','MVSR','SNIS','CVR','GRRR','GNTW','BVRI','MGIT','KMIT','JNTS','VMEG','BVRW','CMRK','MECS','CVSR','BREW','GCTC','NGIT') and Region == 'OU' and Seat_Category in ('BC_D_GEN_OU') ")
df.query("Branch_Code in ( 'AID','CSM','AIM','CSD','CSE','CSI','CSM','CME','CSN','CST','INF','ITE','KITS','MREC','VJIT','STLW','OUCT','JNKR','VBIT','INDU','KUWL','TKEM','MREC') and Caste_Code == 'BC_D' and Gender =='F' and Region == 'OU' and Seat_Category in ('BC_D_GIRLS_OU') and Rank >= 99940 ")

,Institute_Code,Institution Name,Branch_Code,Roll_No,Rank,Candidate Name,Gender,Region,Caste_Code,Seat_Category
50021,SDGI,"SREE DATTHA GRP OF INSTNS, IBRAHIMPATAN",CSD,2123D02598,100109,BANDAMEEDI YASHWIKA,F,OU,BC_D,BC_D_GIRLS_OU
50042,STLW,STANLEY COLLEGE OF ENGG AND TECHNOLOGY FOR WOM...,INF,2124E02028,100162,ADEPU PUNITHEESHWARI,F,OU,BC_D,BC_D_GIRLS_OU
50151,PALV,"PALLAVI ENGINEERING COLLEGE, KUNTLOOR",CSE,2121H02086,100472,KOTLA DIVYA,F,OU,BC_D,BC_D_GIRLS_OU
50154,PETW,"PRINCETON INST OF ENGG TECH FOR WOMEN, GHATKESAR",CSE,2124Q04025,100489,MAHANKALI POOJITHA,F,OU,BC_D,BC_D_GIRLS_OU
50292,TCTK,"TRINITY COLLEGE OF ENGINEERING AND TECHNOLOGY,...",CSE,2121B03312,100865,JILLAKARA BHAVANI,F,OU,BC_D,BC_D_GIRLS_OU
...,...,...,...,...,...,...,...,...,...,...
55116,VMTW,"VIGNANS INST OF MANAGEMENT AND TECH FOR WOMEN,...",CSD,2122L01274,114431,KONTHAM SRILEKHA,F,OU,BC_D,BC_D_GIRLS_OU
55154,MINA,"MINA INST OF ENGG AND TECHNOLOGY FOR WOMEN, MI...",CSM,2122G01018,114549,KALASANI PRAVALLIKA,F,OU,BC_D,BC_D_GIRLS_OU
55220,SISG,"SIDDHARTHA INSTT OF TECHNOLOGY AND SCIENCES, G...",CSM,2121D05051,114761,BANDARI KAVYA,F,OU,BC_D,BC_D_GIRLS_OU
55226,SMSK,"SAMSKRUTHI COLLEGE OF ENGG AND TECHNOLOGY, GHA...",CSD,2124A01065,114789,POLEMONI SAI SUDIPTHA,F,OU,BC_D,BC_D_GIRLS_OU
55373,VMTW,"VIGNANS INST OF MANAGEMENT AND TECH FOR WOMEN,...",CSD,2122G01011,115205,SOMA SATHVIKA,F,OU,BC_D,BC_D_GIRLS_OU

In [13]:
grouped_multiple = df.groupby(['Institute_Code','Institution Name', 'Branch_Code','Gender','Caste_Code','Seat_Category']).agg({'Rank': ['min', 'max']})
grouped_multiple.columns = [ 'Opening_Rank', 'Closing_Rank']
grouped_multiple = grouped_multiple.reset_index()
df2 = pd.DataFrame(grouped_multiple).sort_values('Closing_Rank')

In [25]:
df2.query("Institute_Code in ('BVRI') and Branch_Code in ('CSD', 'CSE', 'CSM', 'CST') and Caste_Code == 'BC_D'")

,Institute_Code,Institution Name,Branch_Code,Gender,Caste_Code,Seat_Category,Opening_Rank,Clsoing_Rank
2502,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSD,F,BC_D,BC_D_GEN_OU,16451,16451
2503,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSD,F,BC_D,BC_D_GIRLS_OU,15180,15180
2512,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSD,M,BC_D,BC_D_GEN_OU,10421,18700
2530,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,F,BC_D,BC_D_CAP_GIRLS_UR(4),115153,115153
2531,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,F,BC_D,BC_D_GEN_OU,13726,13726
2532,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,F,BC_D,BC_D_GEN_UR,7251,7251
2533,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,F,BC_D,BC_D_GIRLS_OU,8119,13529
2534,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,F,BC_D,BC_D_GIRLS_UR,5793,5793
2535,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,F,BC_D,OC_PHV_GIRLS_OU,42409,42409
2562,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,M,BC_D,BC_D_GEN_OU,8868,14145
2563,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,M,BC_D,BC_D_GEN_UR,7183,8344
2564,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSE,M,BC_D,OC_GEN_OU,9220,9220
2580,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSM,F,BC_D,BC_D_GEN_OU,12485,12485
2581,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSM,F,BC_D,BC_D_GIRLS_OU,14500,15549
2593,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSM,M,BC_D,BC_D_CAP_GEN_UR(4),57432,57432
2594,BVRI,"B V RAJU INSTITUTE OF TECHNOLOGY, NARSAPUR",CSM,M,BC_D,BC_D_GEN_OU,9549,16750

In [15]:
k = df2.query("Branch_Code in ( 'AID','CSM','AIM','CSD','CSE','CSI','CSM','CME','CSN','CST','INF','ITE','KITS','MREC','VJIT','STLW','OUCT','JNKR','VBIT','INDU','KUWL','TKEM','MREC') and Caste_Code == 'BC_D' and Gender =='M'")

In [16]:
k.to_csv('/content/drive/MyDrive/AI/TS_Eamcet/Mani.csv')

In [17]:
grouped_multiple = df.groupby(['Institute_Code','Institution Name', 'Branch_Code','Gender','Caste_Code','Seat_Category']).agg({'Rank': ['min', 'max']})
grouped_multiple.columns = [ 'Opening_Rank', 'Clsoing_Rank']
grouped_multiple = grouped_multiple.reset_index()
df2 = pd.DataFrame(grouped_multiple)